# Generated by Django 5.2.11 on 2026-09-27 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agriculteur', 'Agriculteur'), ('acheteur', 'Acheteur'), ('admin', 'Administrateur')], max_length=20, verbose_name='rôle')),
                ('nom', models.CharField(max_length=120, verbose_name='nom complet')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('region', models.CharField(choices=[('Maritime', 'Maritime'), ('Plateaux', 'Plateaux'), ('Centrale', 'Centrale'), ('Kara', 'Kara'), ('Savanes', 'Savanes')], max_length=20, verbose_name='région')),
                ('verifie', models.BooleanField(default=False, verbose_name='vérifié')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
                'db_table': 'profils',
                'ordering': ['nom'],
            },
        ),
    ]
