# Generated by Django 5.2.11 on 2026-09-27 16:43

import annonces.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=140, verbose_name='titre')),
                ('categorie', models.CharField(choices=[('Céréales', 'Céréales'), ('Légumes', 'Légumes'), ('Tubercules & racines', 'Tubercules & racines'), ('Légumineuses', 'Légumineuses'), ('Fruits', 'Fruits'), ('Oléagineux', 'Oléagineux'), ('Épices & condiments', 'Épices & condiments'), ('Autres', 'Autres')], max_length=40, verbose_name='catégorie')),
                ('description', models.TextField(verbose_name='description')),
                ('prix', models.PositiveIntegerField(verbose_name='prix en FCFA')),
                ('unite', models.CharField(choices=[('kg', 'kg'), ('sac', 'sac'), ('tonne', 'tonne')], max_length=10, verbose_name='unité de vente')),
                ('quantite_dispo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantité disponible')),
                ('region', models.CharField(choices=[('Maritime', 'Maritime'), ('Plateaux', 'Plateaux'), ('Centrale', 'Centrale'), ('Kara', 'Kara'), ('Savanes', 'Savanes')], max_length=20, verbose_name='région')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('epuisee', 'Épuisée'), ('suspendue', 'Suspendue')], default='active', max_length=20, verbose_name='statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL, verbose_name='agriculteur')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'db_table': 'annonces',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=annonces.models.chemin_photo, verbose_name='image')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('ajoutee_le', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce', verbose_name='annonce')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'annonce_photos',
                'ordering': ['ordre', 'ajoutee_le'],
            },
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['statut', '-cree_le'], name='idx_annonce_statut_date'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['categorie'], name='idx_annonce_categorie'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['region'], name='idx_annonce_region'),
        ),
    ]
