# Generated by Django 5.2.11 on 2026-09-27 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('sujet', models.CharField(choices=[('vendre', 'Je veux vendre mes produits'), ('acheter', 'Je veux acheter'), ('commande', 'Question sur une commande'), ('paiement', 'Question sur un paiement'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('traite', models.BooleanField(default=False, verbose_name='traité')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_contact', to=settings.AUTH_USER_MODEL, verbose_name='compte')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'db_table': 'messages_contact',
                'ordering': ['traite', '-cree_le'],
            },
        ),
    ]
