# Generated by Django 5.2.11 on 2026-09-27 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('payee', 'Payée'), ('preparee', 'Préparée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('litige', 'Litige')], default='en_attente_paiement', max_length=25, verbose_name='statut')),
                ('total', models.PositiveIntegerField(verbose_name='total en FCFA')),
                ('mode_livraison', models.CharField(choices=[('retrait', 'Retrait sur place'), ('transporteur', 'Livraison par transporteur')], max_length=20, verbose_name='mode de livraison')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='adresse de livraison')),
                ('litige_motif', models.TextField(blank=True, verbose_name='motif du litige')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to=settings.AUTH_USER_MODEL, verbose_name='acheteur')),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='agriculteur')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'db_table': 'commandes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=140, verbose_name="titre au moment de l'achat")),
                ('prix_unitaire', models.PositiveIntegerField(verbose_name='prix unitaire en FCFA')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantité')),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='annonces.annonce', verbose_name='annonce')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'db_table': 'commande_lignes',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(verbose_name='montant en FCFA')),
                ('frais_commission', models.PositiveIntegerField(verbose_name='commission plateforme en FCFA')),
                ('statut_sequestre', models.CharField(choices=[('en_attente', 'En attente'), ('collecte', 'Collecté'), ('sequestre', 'Sous séquestre'), ('libere', 'Libéré'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='statut du séquestre')),
                ('methode', models.CharField(blank=True, choices=[('flooz', 'Flooz (Moov)'), ('mixx', 'Mixx by Yas'), ('carte', 'Carte bancaire')], max_length=20, verbose_name='méthode')),
                ('ref_agregateur', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='référence agrégateur')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'db_table': 'paiements',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='JournalPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut_depart', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('collecte', 'Collecté'), ('sequestre', 'Sous séquestre'), ('libere', 'Libéré'), ('rembourse', 'Remboursé')], max_length=20, verbose_name='statut de départ')),
                ('statut_arrivee', models.CharField(choices=[('en_attente', 'En attente'), ('collecte', 'Collecté'), ('sequestre', 'Sous séquestre'), ('libere', 'Libéré'), ('rembourse', 'Remboursé')], max_length=20, verbose_name="statut d'arrivée")),
                ('acteur', models.CharField(max_length=30, verbose_name='acteur')),
                ('montant', models.PositiveIntegerField(verbose_name='montant en FCFA')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='commandes.paiement', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'entrée de journal',
                'verbose_name_plural': 'journal des paiements',
                'db_table': 'paiement_journal',
                'ordering': ['cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['agriculteur', 'statut'], name='idx_cmd_vendeur'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['acheteur', '-cree_le'], name='idx_cmd_acheteur'),
        ),
    ]
